// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpg8C9MjRPCAjoJmejrW1nNW4Ir79bwU',
    appId: '1:275766655217:web:2e91fc5f58e80dad2d9150',
    messagingSenderId: '275766655217',
    projectId: 'the-hub-d8ea7',
    authDomain: 'the-hub-d8ea7.firebaseapp.com',
    storageBucket: 'the-hub-d8ea7.appspot.com',
    measurementId: 'G-VFMZYN1G9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwFKD5IcJrTi6OVcnsr5DU6PWhASsRtI',
    appId: '1:275766655217:android:44eddfb471d142312d9150',
    messagingSenderId: '275766655217',
    projectId: 'the-hub-d8ea7',
    storageBucket: 'the-hub-d8ea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_KIeoK3ZTWCih6SdKNJf9Ei9t-8JxNLk',
    appId: '1:275766655217:ios:737399f0acc7b8bf2d9150',
    messagingSenderId: '275766655217',
    projectId: 'the-hub-d8ea7',
    storageBucket: 'the-hub-d8ea7.appspot.com',
    iosClientId: '275766655217-1ui0tcose4o2evefeokug6i8soadjdf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.theHubFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_KIeoK3ZTWCih6SdKNJf9Ei9t-8JxNLk',
    appId: '1:275766655217:ios:03846efb4e33811f2d9150',
    messagingSenderId: '275766655217',
    projectId: 'the-hub-d8ea7',
    storageBucket: 'the-hub-d8ea7.appspot.com',
    iosClientId: '275766655217-h1ic5ed9ee9lfgn8e0um19mt1np54rq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.theHubFlutter.RunnerTests',
  );
}
